### ISSUE TITLE
`argb` and `targ` instructions are not described correctly in the documentation

### ISSUE THREAD

**Issue by brona-ruzicka** [newcomb-luke/kOS-KASM#16]
The [Full instruction list](https://newcomb-luke.github.io/kOS-KASM/chapter_2/instructions_list.html) page doesn't mention the `argb` instruction. ~~Which only tests if there is an `ARG marker` on top of the stack. Only `targ` instruction (which instead throws an error if the `ARG marker` isn't there) is described.~~

*Edit: This is false, look below for full explanation.*

**Comment by brona-ruzicka** [comment]
The `argb` instruction in question can be seen on the [Shared libraries](https://newcomb-luke.github.io/kOS-KASM/chapter_5/shared_libraries.html#in-kerboscript) page. Specifically in the decompiled `@LR00` code, under the `pop_loop` label.

**Comment by brona-ruzicka** [comment]
I just looked at it again and it's more complicated than that.

In the docs, the description for the supposed `targ` instuction is actually talking about the `argb` instruction.

So instead of this
> **targ** - Asserts that the topmost thing on the stack is an argument marker (throws a kOS error if it isn't!)

The docs should look like this
> **argb** - Asserts that the topmost thing on the stack is an argument marker (throws a kOS error if it isn't!)
> **targ** - Tests if the topmost thing on the stack is an argument marker and pushes a true on top if it is, or false if it is not.

The correct descriptions are available [here](https://github.com/newcomb-luke/kOS-KLinker/blob/main/docs/Instruction-docs.md#argument-bottom).

**Comment by brona-ruzicka** [comment]
The same problem is also on the already mentioned [Shared libraries](https://newcomb-luke.github.io/kOS-KASM/chapter_5/shared_libraries.html#in-kerboscript) page.

The `argb` instuction I was referring to earlier should in fact be a `targ` instruction. As visible [here](https://github.com/KSP-KOS/KOS/blob/15ced11a1657fe4d767950f9ebcba62dc094deed/src/kOS.Safe/Compilation/ProgramBuilder.cs#L146).

**Comment by newcomb-luke** [comment]
Thank you for pointing that out, I am going to try to fix the docs.

**Comment by newcomb-luke** [comment]
This has just been fixed in the gh-pages branch and the fix is live.
